//
//  CardContext.swift
//  楊昀恩生日欸
//
//  Created by Andy Lin on 2024/2/6.
//

import Foundation
import SwiftUI

enum ContextType: Codable {
    case defaultContent, contentAfterVisit10Times, cardNonsense, graduateGreeting, memories, newNonsence, noGraduation, aSmartHumanSaid, noGraduation2, finalGraduationGreeting, finalGraduationGreeting_article, watchMainFirst
}

final class CardContext {
    var contextType: ContextType
    
    init(contextType: ContextType = .defaultContent) {
        self.contextType = contextType
    }
    
    var content: [CardContentItem] {
        switch contextType {
        case .defaultContent:
            return defaultContent
        case .contentAfterVisit10Times:
            return contentAfterVisit10Times
        case .cardNonsense:
            return cardNonsense
        case .graduateGreeting:
            return graduateGreeting
        case .memories:
            return memories
        case .newNonsence:
            return newNonsence
        case .noGraduation:
            return noGraduation
        case .aSmartHumanSaid:
            return aSmartHumanSaid
        case .noGraduation2:
            return noGraduation2
        case .finalGraduationGreeting:
            return finalGraduationGreeting
        case .watchMainFirst:
            return watchMainFirst
        default:
            return [.init(text: "ERROR")]
        }
    }
    
    fileprivate static let pushTimes = 1
    
    let defaultContent: [CardContentItem] = [
        CardContentItem(text: "Tap to see moreeeee"),
        CardContentItem(text: "Left is back"),
        CardContentItem(text: "Right is continue"),
        CardContentItem(text: "welcome to your birthday greeting"),
        CardContentItem(text: "just watch "),
        CardContentItem(text: "and"),
        CardContentItem(text: "enjoy it :D"),
        CardContentItem(text: ""),
        CardContentItem(text: "欸你好"),
        CardContentItem(text: "這是我給你的生日禮物"),
        CardContentItem(text: "驚不驚喜 E不EY"),
        CardContentItem(text: "想必沒人給你過這種生日禮物8️⃣"),
        CardContentItem(text: "哎呀你那時候就在那裡問"),
        CardContentItem(text: "不是說了之後自己會知道唄"),
        CardContentItem(text: "總之"),
        CardContentItem(text: "你一定是非常高興收到這個對吧:D"),
        CardContentItem(text: "欸你看"),
        CardContentItem(text: "你總共開了這個app \(pushTimes)次ㄟ"),
        CardContentItem(text: "好啦這個功能是那次更新才加上去ㄉ\n所以可能會不準:D"),
        CardContentItem(text: "嗯對 ㄜ"),
        CardContentItem(text: "生日禮物的部分"),
        CardContentItem(text: "我很抱歉🙃"),
        CardContentItem(text: "🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️"),
        CardContentItem(text: ""),
        CardContentItem(text: "這就當作是你給我的禮物的回禮好ㄌ"),
        CardContentItem(text: "好啦，㊗️你生日快樂"),
        CardContentItem(text: "", image: Image("BirthdayGreeting")),
        CardContentItem(text: "用你的魔法打敗你:D"),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "我多想一次"),
        CardContentItem(text: "試都考高 比賽都贏 不會遇到爛桃花"),
        CardContentItem(text: "多送第四個給你自己選ㄅ"),
        CardContentItem(text: "有空記得常來看看這些廢話(·▷．)"),
        CardContentItem(text: "搞不好會有你意想不到的東東:D"),
        CardContentItem(text: "好啦 廢話好像有點太多ㄌ\n講點正經的好了"),
        CardContentItem(text: "這段從國小開始的緣分（？"),
        CardContentItem(text: "好像是快要結束了餒：（"),
        CardContentItem(text: "這樣看一看 雖然我們才比較熟快一年而已"),
        CardContentItem(text: "阿但是好像真的挺多東西能拿出來講"),
        CardContentItem(text: "但這一年裡面我不知道惹了多少事:D"),
        CardContentItem(text: "而且好像也挺多事情發生ㄉ"),
        CardContentItem(text: "從一開始你來找我 那位柏寬🈹"),
        CardContentItem(text: "還有3月的那個11的事情（好我很對不起他：）"),
        CardContentItem(text: "到大概4月之後的自信🈹&那位人見人愛ㄉ婷涵:D"),
        CardContentItem(text: "之後你開始跟我說10一天到晚在那裡靠腰很煩"),
        CardContentItem(text: "後來6 7月"),
        CardContentItem(text: "ㄜ 耳環事件我就不多說了"),
        CardContentItem(text: "後面的我好像也幾乎忘了"),
        CardContentItem(text: "欸對"),
        CardContentItem(text: "還有你給我生日禮物"),
        CardContentItem(text: "不用客氣la"),
        CardContentItem(text: "阿但是沒關係"),
        CardContentItem(text: "在這之間充斥著所有時間線的就是你的一某:D"),
        CardContentItem(text: "雖然最近你不怎麼理我"),
        CardContentItem(text: "訊息都過好幾個小時才回：（"),
        CardContentItem(text: "啊但我還是回禮一下好了"),
        CardContentItem(text: "嗯對還是感謝一下你教我歷史好了:D"),
        CardContentItem(text: "還有那個設計到一半的東東：（"),
        CardContentItem(text: "你呢"),
        CardContentItem(text: "都會在那邊"),
        CardContentItem(text: "欸很扯欸 校車上/回去訊息講"),
        CardContentItem(text: "然後講著講著就不講ㄌ"),
        CardContentItem(text: "在那裡吊胃口"),
        CardContentItem(text: "。"),
        CardContentItem(text: "說到這個"),
        CardContentItem(text: "你還沒跟我說你為什麼你要在那裡"),
        CardContentItem(text: "什麼比目魚 中央空調ㄉ"),
        CardContentItem(text: "跟我講啦拜託( •᷄⌓•᷅ )"),
        CardContentItem(text: ""),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "最後"),
        CardContentItem(text: "再祝你生日快樂一次"),
        CardContentItem(text: "不要太在意其他人怎麼評價你la"),
        CardContentItem(text: "他們愛嘴賤就讓他們去賤唄"),
        CardContentItem(text: "還有"),
        CardContentItem(text: "謝謝你"),
        CardContentItem(text: ":D"),
        CardContentItem(text: "", isShowButton: true),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "ㄟ", isShowButton: false),
        CardContentItem(text: "你怎麼還在"),
        CardContentItem(text: "不要太喜歡這個啦:D"),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "給你看一些製作的東東好ㄌ"),
        CardContentItem(text: "你看我多用心ㄚ", image: Image("MakingDetail")),
        CardContentItem(text: "", isShowButton: true),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "偷偷跟你講個秘密", isShowButton: false),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "期待嗎"),
        CardContentItem(text: "期待就先跟我講這個是什麼👀", image: Image("ReasonOfFlounder")),
        CardContentItem(text: ""),
        CardContentItem(text: "", isShowButton: true),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "吼呦", isShowButton: false),
        CardContentItem(text: "你怎麼還在啦"),
        CardContentItem(text: "你是不是真的以為我會寫什麼👀"),
        CardContentItem(text: "沒有這種事情好ㄇ"),
        CardContentItem(text: "我可以給你看你的照片👌🏻"),
        CardContentItem(text: "雖然沒多少就是了：）"),
        CardContentItem(text: "這是你在校車上被偷拍:D", image: Image("SheOnSchoolBus")),
        CardContentItem(text: "還有同場加映", image: Image("SheOnSchoolBus2")),
        CardContentItem(text: "欸還有你在那裡一某", image: Image("EmoText")),
        CardContentItem(text: "不要忘記這個你說眼睛ㄆㄧㄚˊ掉ㄉ", image: Image("SchoolFail")),
        CardContentItem(text: "喔對 還有這個"),
        CardContentItem(text: "我直接躲到超旁邊:D", image: Image("GraduationTrip-GroupPhoto")),
        CardContentItem(text: "你知道這張辛拉麵那一天一直說8拍得很好，講超久：）", image: Image("GraduationTrip")),
        CardContentItem(text: "還有這個啦 皮老闆:D", image: Image("Plankton")),
        CardContentItem(text: "好啦後面是真的沒有東西ㄌ"),
        CardContentItem(text: "給我按那個返回", isShowButton: true),
        CardContentItem(text: "繼續按你也按不出什麼東西:D"),
        CardContentItem(text: ""),
        CardContentItem(text: "夠了我要強制驅離ㄌ")
    ]
    
    let contentAfterVisit10Times: [CardContentItem] = [
        CardContentItem(text: "欸你知道ㄇ"),
        CardContentItem(text: "這是你看超過10次之後會出現ㄉ"),
        CardContentItem(text: "如果你想要回去原本ㄉ東東"),
        CardContentItem(text: "多看完幾次就會回去ㄌ:D（大概2次ㄅ）"),
        CardContentItem(text: "既然你都看這麼多次ㄌ"),
        CardContentItem(text: "想必是對這東西很有愛對吧👀"),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "說真的"),
        CardContentItem(text: "如果你真的看到這個了"),
        CardContentItem(text: "我很感動"),
        CardContentItem(text: "是真的很感動：）"),
        CardContentItem(text: "還有"),
        CardContentItem(text: "沒帶到你的氣球我真的很抱歉：（"),
        CardContentItem(text: "欸對你知道ㄇ"),
        CardContentItem(text: "這個東東ㄚ"),
        CardContentItem(text: "過90天就會消失了"),
        CardContentItem(text: "不是我刪掉他"),
        CardContentItem(text: "是他本身TestFlight的限制"),
        CardContentItem(text: "如果你想一直留著的話"),
        CardContentItem(text: "記得叫我去更新:D"),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "不知道你過得怎樣"),
        CardContentItem(text: "也不知道你什麼時候會看到這個"),
        CardContentItem(text: "也許根本沒有看到也說不定:D"),
        CardContentItem(text: ""),
        CardContentItem(text: "如果"),
        CardContentItem(text: "你看到這個"),
        CardContentItem(text: "祝你會考能順利考上你嚮往的學校"),
        CardContentItem(text: "唉呀"),
        CardContentItem(text: "我人真的太好了:D"),
        CardContentItem(text: ""),
        CardContentItem(text: "ㄞ"),
        CardContentItem(text: "國中生活還真的要結束了欸"),
        CardContentItem(text: ""),
        CardContentItem(text: "好..不真實（？"),
        CardContentItem(text: "一切都發生得那麼快"),
        CardContentItem(text: "一轉眼間"),
        CardContentItem(text: "從我們開始認識的國二"),
        CardContentItem(text: "到現在已經他媽國三要畢業了"),
        CardContentItem(text: "。"),
        CardContentItem(text: "我"),
        CardContentItem(text: "不知道講什麼"),
        CardContentItem(text: "過得好快"),
        CardContentItem(text: "真的好快"),
        CardContentItem(text: "就好像是一段旅行"),
        CardContentItem(text: "感覺才剛踏上啟程的路途"),
        CardContentItem(text: "馬上就結束了一樣"),
        CardContentItem(text: "我也知道除了11那群以外對你來說基本沒什麼好留念ㄉ"),
        CardContentItem(text: "（聽說你覺得都是在勾心鬥角:D"),
        CardContentItem(text: "好ㄅ"),
        CardContentItem(text: "感覺我也想不到什麼要講的ㄌ"),
        CardContentItem(text: "剩的如果你還想聽"),
        CardContentItem(text: "你去訊息提醒我講:D\n我還有記得的話la"),
        CardContentItem(text: "那就先醬子唄", isShowButton: true),
        CardContentItem(text: "可以離開ㄌ"),
        CardContentItem(text: "後面沒東西了"),
        CardContentItem(text: ""),
        CardContentItem(text: "")
    ]
    
    let cardNonsense: [CardContentItem] = [
        CardContentItem(text: "好啦不要再點ㄌ"),
        CardContentItem(text: "快點點那個信封啦"),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "吼呦"),
        CardContentItem(text: "聽不懂ㄇ"),
        CardContentItem(text: "我要強制你進去ㄌ")
    ]
    
    let graduateGreeting: [CardContentItem] = [
        CardContentItem(text: "ㄟ嘿"),
        CardContentItem(text: "想不到8️⃣"),
        CardContentItem(text: "又是新的玩法"),
        CardContentItem(text: "我真厲害"),
        CardContentItem(text: "承認我是天才ㄅ"),
        CardContentItem(text: "3D的欸"),
        CardContentItem(text: "看吧"),
        CardContentItem(text: "這超厲害"),
        CardContentItem(text: "反正到時候如果back出現你可能也不會按"),
        CardContentItem(text: "那就乾脆直接弄一本書"),
        CardContentItem(text: "你也退出不了:D"),
        CardContentItem(text: "欸而且"),
        CardContentItem(text: "這是我第一次有畢業典禮😂"),
        CardContentItem(text: "有夠可悲"),
        CardContentItem(text: "國小沒有畢典：（"),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "廢話不多說"),
        CardContentItem(text: ":D"),
        CardContentItem(text: "你看到這個的時候應該已經畢業了吧？"),
        CardContentItem(text: "至少我是這麼預定的ㄌㄚ"),
        CardContentItem(text: "ㄣ"),
        CardContentItem(text: "不知道你上了哪所高中"),
        CardContentItem(text: "不知道你的會考成績如何"),
        CardContentItem(text: "也不知道我們之後到底會不會再繼續聊天"),
        CardContentItem(text: ""),
        CardContentItem(text: "ㄞ"),
        CardContentItem(text: "三年 好像就真的這樣過去了ㄟ"),
        CardContentItem(text: "這之間的各種往事"),
        CardContentItem(text: "什麼都體驗過"),
        CardContentItem(text: "卻又說什麼都沒辦法接受它已經要結束了的事實"),
        CardContentItem(text: "好希望這一切都只是假的"),
        CardContentItem(text: "希望這不要結束"),
        CardContentItem(text: "唉可惜了 \n：）"),
        CardContentItem(text: "欸對"),
        CardContentItem(text: "如果你有看到那個什麼"),
        CardContentItem(text: "你看這個ㄟㄆ超過10次的那個"),
        CardContentItem(text: "我會很感動🫶🏻"),
        CardContentItem(text: ""),
        CardContentItem(text: "好吧"),
        CardContentItem(text: "畢業快樂"),
        CardContentItem(text: "🎓"),
        CardContentItem(text: "我知道啦"),
        CardContentItem(text: "那個賈伯斯的"),
        CardContentItem(text: "Stay hungry"),
        CardContentItem(text: "Stay foolish"),
        CardContentItem(text: "給個畢業祝福好了"),
        CardContentItem(text: "希望你上高中也能搞好人際關係"),
        CardContentItem(text: "不要整天一某:D"),
        CardContentItem(text: "還有"),
        CardContentItem(text: "讀書變很輕鬆"),
        CardContentItem(text: "直接開竅👍🏻"),
        CardContentItem(text: "你看我人多好ㄚ"),
        CardContentItem(text: "還幫你祝福那麼多", isShowButton: true),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "欸", isShowButton: false),
        CardContentItem(text: "你還在ㄚ"),
        CardContentItem(text: "感動ㄟ（雖然你也退出不了😂"),
        CardContentItem(text: "我不知道怎麼結尾欸"),
        CardContentItem(text: "前面講那麼多"),
        CardContentItem(text: "突然不知道要怎麼結尾了"),
        CardContentItem(text: "超好笑"),
        CardContentItem(text: "還是你來幫我想:D", isShowButton: true),
        CardContentItem(text: ""),
        CardContentItem(text: "", isShowButton: false),
        CardContentItem(text: "好吧"),
        CardContentItem(text: "我來講一下你的這個禮物我藏的所有彩蛋好ㄌ"),
        CardContentItem(text: "有些真的是無聊到我也不知道為什麼我會要放這個😂"),
        CardContentItem(text: "來首先是第一個"),
        CardContentItem(text: "這個是不是很眼熟", image: Image("Egg-16e")),
        CardContentItem(text: "你知道為什麼是長這樣ㄇ"),
        CardContentItem(text: "你去算一下這有幾個e"),
        CardContentItem(text: "第一面總共7個"),
        CardContentItem(text: "全部的的話是16個"),
        CardContentItem(text: "看我多厲害ㄚ"),
        CardContentItem(text: "然後接下來是"),
        CardContentItem(text: "這個", image: Image("Egg-Donald")),
        CardContentItem(text: "是在致敬你給我的生日卡片旁邊那隻可愛ㄉ唐老鴨"),
        CardContentItem(text: "", image: Image("CardGaveToMe")),
        CardContentItem(text: "只是我找不到旁邊那個貼紙：（"),
        CardContentItem(text: "所以史努比就沒放ㄌ"),
        CardContentItem(text: "然後"),
        CardContentItem(text: "還有還有"),
        CardContentItem(text: "最開始"),
        CardContentItem(text: "你ㄉ生日還沒到的時候"),
        CardContentItem(text: "不是有那個"),
        CardContentItem(text: "點螢幕就有一堆廢話跑出來"),
        CardContentItem(text: "這個ㄚ"),
        CardContentItem(text: "你點7次是第一條"),
        CardContentItem(text: "點11次是第二條"),
        CardContentItem(text: "點16次是第三條"),
        CardContentItem(text: "後面還有一個"),
        CardContentItem(text: "34次是第6條"),
        CardContentItem(text: "然後其他的都是隨便的數字"),
        CardContentItem(text: "欸 拜託"),
        CardContentItem(text: "作者還是可以留名一下ㄉ好嗎👌🏻"),
        CardContentItem(text: "這代表什麼"),
        CardContentItem(text: "讓我想想"),
        CardContentItem(text: "ㄜ"),
        CardContentItem(text: "一定是什麼"),
        CardContentItem(text: "代表你們三個可以永不分離"),
        CardContentItem(text: "對8️⃣"),
        CardContentItem(text: ":D"),
        CardContentItem(text: "還有就是"),
        CardContentItem(text: "當你開這個app超過10次"),
        CardContentItem(text: "他會跳出來一個特別篇"),
        CardContentItem(text: "裡面也沒什麼"),
        CardContentItem(text: "但就是多講了一些話"),
        CardContentItem(text: "而且不知道你有沒有發現"),
        CardContentItem(text: "就是"),
        CardContentItem(text: "我有說"),
        CardContentItem(text: "：有空記得常回來看"),
        CardContentItem(text: "：搞不好會有你想不到的東西(·▷．)"),
        CardContentItem(text: "看吧"),
        CardContentItem(text: "都講過了"),
        CardContentItem(text: "有沒有被發現而已😀"),
        CardContentItem(text: "讓我再想想"),
        CardContentItem(text: "喔對"),
        CardContentItem(text: "還有那個"),
        CardContentItem(text: "我在你生日當天的通知"),
        CardContentItem(text: "有7.16.11秒送出的通知"),
        CardContentItem(text: "酷ㄅ"),
        CardContentItem(text: "let me想一下還有什麼"),
        CardContentItem(text: "ㄛ對啦"),
        CardContentItem(text: "還有那個"),
        CardContentItem(text: "不是有後面點很多下才出現的彩蛋ㄇ"),
        CardContentItem(text: "那個分別是7下11下16下"),
        CardContentItem(text: "ㄣ"),
        CardContentItem(text: "好像還有其他的"),
        CardContentItem(text: "但"),
        CardContentItem(text: "我目前想不到"),
        CardContentItem(text: "想到再說唄"),
        CardContentItem(text: "欸對你知道嗎"),
        CardContentItem(text: "我這個作品有上傳ㄛ"),
        CardContentItem(text: "酷吧"),
        CardContentItem(text: ""),
        CardContentItem(text: "好"),
        CardContentItem(text: "我沒話講了"),
        CardContentItem(text: "那就"),
        CardContentItem(text: "ㄜ"),
        CardContentItem(text: "掰掰"),
        CardContentItem(text: ":D", isShowButton: true),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "沒有啦開玩笑的", isShowButton: false),
        CardContentItem(text: "我怎麼可能沒話講了"),
        CardContentItem(text: "我想講的話超多欸"),
        CardContentItem(text: "比公民老師話癆"),
        CardContentItem(text: "搞笑的還是真的想講的"),
        CardContentItem(text: "全部弄出來可能有快千字（一定是這樣的好嗎"),
        CardContentItem(text: "我想得到的話再講ㄅ"),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "這個章節就在這裡畫上句號ㄌ"),
        CardContentItem(text: "掰:D")
    ]
    
    let newNonsence: [CardContentItem] = [
        CardContentItem(text: "欸"),
        CardContentItem(text: "你好啊"),
        CardContentItem(text: "要會考了ㄟ"),
        CardContentItem(text: "ㄍㄢ"),
        CardContentItem(text: "讀不完了啦"),
        CardContentItem(text: "我也不知道你那時候還會剩幾天"),
        CardContentItem(text: "啊那我就做個會考倒數好了"),
        CardContentItem(text: "出去左轉就有了:D", isShowButton: true),
        CardContentItem(text: "好啦沒有啦開玩笑的", isShowButton: false),
        CardContentItem(text: "我也沒那個時間去做了"),
        CardContentItem(text: "真的要的話我明年可以送你😎"),
        CardContentItem(text: "啊是誰啊"),
        CardContentItem(text: "叫我再更新這個:D"),
        CardContentItem(text: "很愛是嗎"),
        CardContentItem(text: "跟你講ㄛ"),
        CardContentItem(text: "好吧\n我也不知道講什麼"),
        CardContentItem(text: "沒關係"),
        CardContentItem(text: "最近還好嗎"),
        CardContentItem(text: "會考ㄚ"),
        CardContentItem(text: "段考ㄚ"),
        CardContentItem(text: "模考ㄚ"),
        CardContentItem(text: "ㄍㄢ啊怎麼那麼多東西都排在四月。"),
        CardContentItem(text: "欸雖然壓力很大"),
        CardContentItem(text: "很煩"),
        CardContentItem(text: "可能覺得怎麼準備都學不會"),
        CardContentItem(text: "但不要放棄"),
        CardContentItem(text: "真的不要放棄"),
        CardContentItem(text: "不放棄至少還有一點機會"),
        CardContentItem(text: "放了真的就什麼都沒了💩"),
        CardContentItem(text: "加油"),
        CardContentItem(text: "😃"),
        CardContentItem(text: "相信自己"),
        CardContentItem(text: "喔然後還有"),
        CardContentItem(text: "到底誰跟你說的有情緒不處理是成熟"),
        CardContentItem(text: "是堅強"),
        CardContentItem(text: "是好事啊"),
        CardContentItem(text: "=="),
        CardContentItem(text: "有情緒就處理ㄚ"),
        CardContentItem(text: "又不是矯情"),
        CardContentItem(text: "你這是什麼被扭曲的三觀"),
        CardContentItem(text: "❓"),
        CardContentItem(text: "有情緒就好好面對它"),
        CardContentItem(text: "不要一直放在心裡"),
        CardContentItem(text: "這樣總有一天會爆ㄉ"),
        CardContentItem(text: "相信你也不會想某天特別不爽然後直接來一個爆炸ㄅ"),
        CardContentItem(text: "不要再被其他人的那種被扭曲的三觀影響了啦"),
        CardContentItem(text: "講到扭曲的三觀"),
        CardContentItem(text: "到底為什麼你會一直覺得你的腳很粗"),
        CardContentItem(text: "❓❓"),
        CardContentItem(text: "還有一直說自己很黑"),
        CardContentItem(text: "❓❓❓"),
        CardContentItem(text: "健康最重要啦‼️"),
        CardContentItem(text: "在那邊都不吃飯"),
        CardContentItem(text: "你這已經超過標準很多了好嗎👌🏻"),
        CardContentItem(text: "不是往下超過"),
        CardContentItem(text: "不要給我亂解讀：）"),
        CardContentItem(text: ""),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "最後的最後"),
        CardContentItem(text: "你想按這按鈕退出就按這按鈕", isShowButton: true),
        CardContentItem(text: "不想的話我也是會強制驅逐👍🏻"),
        CardContentItem(text: "反正", isShowButton: false),
        CardContentItem(text: "我想說的是"),
        CardContentItem(text: "考試加油"),
        CardContentItem(text: "😃")
    ]
    
    let memories: [CardContentItem] = [
        CardContentItem(text: "ㄟ"),
        CardContentItem(text: "你點進來這個了"),
        CardContentItem(text: "是不是很期待ㄚ"),
        CardContentItem(text: "跟你說ㄛ"),
        CardContentItem(text: "我也很期待"),
        CardContentItem(text: "這裡就是放很多我拍的一些照片而已"),
        CardContentItem(text: "然後講個幹話"),
        CardContentItem(text: "反正"),
        CardContentItem(text: "等等就看唄"),
        CardContentItem(text: "但由於我真的沒啥你的照片"),
        CardContentItem(text: "so"),
        CardContentItem(text: "一堆截圖"),
        CardContentItem(text: "：）"),
        CardContentItem(text: "然後"),
        CardContentItem(text: "我也很希望能照時間放照片"),
        CardContentItem(text: "但真的沒辦法"),
        CardContentItem(text: "那些截圖很多都是剛截的"),
        CardContentItem(text: "找不到時間ㄌ"),
        CardContentItem(text: ": ("),
        CardContentItem(text: "欸對"),
        CardContentItem(text: "我們會認識"),
        CardContentItem(text: "還是因為你中檢沒帶證件"),
        CardContentItem(text: "超好笑"),
        CardContentItem(text: "我跟大家認識的過程都好奇怪"),
        CardContentItem(text: "好我要放照片ㄌ"),
        CardContentItem(text: "這好像是我們才剛認識沒多久（？", image: Image("MiddleFinger")),
        CardContentItem(text: "你還記得嗎\n這是你教我歷史，我那時候不在家還拿手機做筆記", image: Image("FirstCall")),
        CardContentItem(text: "欸對"),
        CardContentItem(text: "這是我第一次跟女生講電話 :D"),
        CardContentItem(text: "超好笑"),
        CardContentItem(text: "然後是婷涵", image: Image("Tinghan")),
        CardContentItem(text: "滿滿ㄉ自信🈹小丑紀錄🤡", image: Image("Tinghan")),
        CardContentItem(text: "接下來這個", image: Image("SheOnSchoolBus")),
        CardContentItem(text: "跟這個", image: Image("SheOnSchoolBus2")),
        CardContentItem(text: "都是國二好像才認識沒多久的時候拍的"),
        CardContentItem(text: "還是什麼時候我也忘了：）"),
        CardContentItem(text: "欸對 這張我講完海蟑螂你就去睡覺了", image: Image("Plankton")),
        CardContentItem(text: "：（"),
        CardContentItem(text: "真可借 :D"),
        CardContentItem(text: "欸然後是這個", image: Image("BeLikeImage")),
        CardContentItem(text: "到底哪裡像：（", image: Image("BeLikeImage")),
        CardContentItem(text: "然後你看", image: Image("SchoolFail")),
        CardContentItem(text: "還有這個", image: Image("TyingHair")),
        CardContentItem(text: "都是在校慶的時候少數幾張有你ㄉ照片"),
        CardContentItem(text: "再後來 這是畢旅", image: Image("GraduationTrip-GroupPhoto")),
        CardContentItem(text: "還有這個", image: Image("GraduationTrip")),
        CardContentItem(text: "然後這個是我們在那裡玩螢光棒😂", image: Image("PlayingGlowSticks2")),
        CardContentItem(text: "還有你綁兩邊", image: Image("PlayingGlowSticks")),
        CardContentItem(text: "欸那時候真的超好玩"),
        CardContentItem(text: "還有"),
        CardContentItem(text: "這是最重要ㄉ"),
        CardContentItem(text: "聽說是不到100齁：）", image: Image("MyBDGift")),
        CardContentItem(text: "然後這超煩 你還是沒講", image: Image("ReasonOfFlounder")),
        CardContentItem(text: "然後這超好笑 你還畫在張腳上😂", image: Image("HappyBDOnHand")),
        CardContentItem(text: "接下來是這個"),
        CardContentItem(text: "欸這個學姊超唱歌厲害", image: Image("GreatSinger")),
        CardContentItem(text: "欸你還記得這個嗎😂", image: Image("KeepLaughing")),
        CardContentItem(text: "超好笑他那時候不知道在笑什麼"),
        CardContentItem(text: "然後"),
        CardContentItem(text: "過年"),
        CardContentItem(text: "好像沒有什麼東西"),
        CardContentItem(text: "那我放張101煙火好ㄌ", image: Image("Fireworks")),
        CardContentItem(text: "好ㄉ"),
        CardContentItem(text: "美好的2023就此結束"),
        CardContentItem(text: "進入到個人不怎麼喜歡的2024"),
        CardContentItem(text: "剛過完年就是", image: Image("MadeByPlastic")),
        CardContentItem(text: "❓", image: Image("HerDraw")),
        CardContentItem(text: "你設計到一半烙幹ㄉ", image: Image("MemoodContent")),
        CardContentItem(text: "然後這是你的生日蛋糕", image: Image("Icon")),
        CardContentItem(text: "看我多有心ㄚ"),
        CardContentItem(text: "ㄣ 那時候搞超久 超好笑", image: Image("SheHasBeenInvited")),
        CardContentItem(text: "然後ㄚ 跟你講 這絕對比那個52分鐘值得多ㄌ", image: Image("ScienceTeaching")),
        CardContentItem(text: "ㄟ 是醜魚欸", image: Image("WaterBottle")),
        CardContentItem(text: "Emo~~", image: Image("EmoText2")),
        CardContentItem(text: "貼圖:D", image: Image("Sticker")),
        CardContentItem(text: "天ㄚ愛死ㄌ 漂釀😍😍😍", image: Image("HasBeenLiked")),
        CardContentItem(text: "欸 要不是我有你電話 不然你回不了家ㄟ", image: Image("HerPhone")),
        CardContentItem(text: "好吧"),
        CardContentItem(text: "差不多就醬ㄌ"),
        CardContentItem(text: "其實還有很多我想放ㄉ"),
        CardContentItem(text: "但考慮到我真的沒有太多時間"),
        CardContentItem(text: "反正就"),
        CardContentItem(text: "ㄜ"),
        CardContentItem(text: "欸對"),
        CardContentItem(text: "有一首歌很好聽"),
        CardContentItem(text: "你去查查看"),
        CardContentItem(text: "サクラキミワタシ"),
        CardContentItem(text: "羅馬拼音是"),
        CardContentItem(text: "sakurakimiwatashi"),
        CardContentItem(text: "歌詞是畢業ㄉ"),
        CardContentItem(text: "個人覺得很好聽:D"),
        CardContentItem(text: "阿然後"),
        CardContentItem(text: "歌詞也挺有意境ㄉ"),
        CardContentItem(text: "雖然你可能也不會去聽：）"),
        CardContentItem(text: "好ㄌ"),
        CardContentItem(text: "先醬ㄅ"),
        CardContentItem(text: "我也沒什麼要講的了（吧？"),
        CardContentItem(text: "掰"),
        CardContentItem(text: ":D")
    ]
    
    let otherNonsence: [CardContentItem] = [
        CardContentItem(text: "我發現一件事"),
        CardContentItem(text: "那就是"),
        CardContentItem(text: "我好閒喔"),
        CardContentItem(text: "還有時間在這裡跟你做這個"),
        CardContentItem(text: "超無聊😂"),
        CardContentItem(text: "欸你知道嗎"),
        CardContentItem(text: "我也不知道我要講什麼"),
        CardContentItem(text: "反正你能看到這個"),
        CardContentItem(text: "肯定是你的福氣好嗎👌🏻"),
        CardContentItem(text: "來老實講"),
        CardContentItem(text: "你到底"),
        CardContentItem(text: "有沒有信心"),
        CardContentItem(text: "會考的部分😀"),
        CardContentItem(text: "來"),
        CardContentItem(text: "我也不知道剩幾天"),
        CardContentItem(text: "酷欸"),
        CardContentItem(text: "完蛋了"),
        CardContentItem(text: "…"),
        CardContentItem(text: "：）"),
        CardContentItem(text: ""),
        CardContentItem(text: "怎麼感覺我會死ㄚ"),
        CardContentItem(text: "ㄍㄢ"),
        CardContentItem(text: "怎麼辦"),
        CardContentItem(text: "我現在超挫"),
        CardContentItem(text: "怎麼辦啦"),
        CardContentItem(text: "完蛋"),
        CardContentItem(text: "我什麼都不會"),
        CardContentItem(text: "ㄍㄢ"),
        CardContentItem(text: "會不會到時候沒高中"),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "欸我突然發現"),
        CardContentItem(text: "我廢話好多ㄛ"),
        CardContentItem(text: "真的超無聊"),
        CardContentItem(text: "超好笑"),
        CardContentItem(text: "好"),
        CardContentItem(text: "這堆廢話要結束ㄌ"),
        CardContentItem(text: "81")
    ]

#if DEBUG
    let testArray: [CardContentItem] = [
        .init(text: "Page 1"),
        .init(text: "Page 2"),
        .init(text: "Page 3")
    ]
#endif
    
    let noGraduation: [CardContentItem] = [
        CardContentItem(text: "好ㄉ"),
        CardContentItem(text: "你點進來ㄌ"),
        CardContentItem(text: "開心了ㄇ"),
        CardContentItem(text: "沒有畢業要看什麼畢業紀念冊"),
        CardContentItem(text: "ㄏㄚˊ？"),
        CardContentItem(text: "好ㄚ"),
        CardContentItem(text: "都醬子ㄚ"),
        CardContentItem(text: "我都弄一個鎖在那裡ㄌ"),
        CardContentItem(text: "好笑ㄇ"),
        CardContentItem(text: ""),
        CardContentItem(text: "欸嘿"),
        CardContentItem(text: "你點進來了"),
        CardContentItem(text: "還是什麼都沒得到"),
        CardContentItem(text: "ㄏㄚㄏㄚ"),
        CardContentItem(text: ":D"),
    ]
    
    let noGraduation2: [CardContentItem] = [
        CardContentItem(text: "你以為"),
        CardContentItem(text: "在畢業前點進來"),
        CardContentItem(text: "我會讓你看這個ㄇ"),
        CardContentItem(text: "ㄏㄚˊ"),
        CardContentItem(text: "我有那麼善良就好了：）")
    ]
    
    let aSmartHumanSaid: [CardContentItem] = [
        CardContentItem(text: "有位智者曾說道："),
        CardContentItem(text: "“人生"),
        CardContentItem(text: "就像一條條看似毫無交集的平行線"),
        CardContentItem(text: "可微風輕拂"),
        CardContentItem(text: "造化弄人"),
        CardContentItem(text: "便有了縱橫交錯"),
        CardContentItem(text: "理不清，理還亂的交集”"),
        CardContentItem(text: "不愧是文科天才"),
        CardContentItem(text: "文筆就是不一樣"),
        CardContentItem(text: ":D")
    ]
    
    let finalGraduationGreeting: [CardContentItem] = [
        CardContentItem(text: "接下來的內容有點多"),
        CardContentItem(text: "如果可以的話"),
        CardContentItem(text: "找個能一次看完的時間唄"),
        CardContentItem(text: "然後"),
        CardContentItem(text: "我先為遲到的事情道歉"),
        CardContentItem(text: "對不起"),
        CardContentItem(text: ":D"),
        CardContentItem(text: "專案爛掉 整個開不起來"),
        CardContentItem(text: "開完之後git不知道為什麼也爛了"),
        CardContentItem(text: "明明我之前甚至完全沒動過這個專案"),
        CardContentItem(text: "然後更慘的是"),
        CardContentItem(text: "還有那個檔案直接不見的"),
        CardContentItem(text: "＝＝"),
        CardContentItem(text: "煩都煩死了"),
        CardContentItem(text: "好ㄉ"),
        CardContentItem(text: "正文開始"),
        CardContentItem(text: "戴上耳機"),
        CardContentItem(text: "開啟勿擾"),
        CardContentItem(text: "為往後的內容得到最佳體驗"),
        CardContentItem(text: ""),
        CardContentItem(text: "ㄏㄟˋ"),
        CardContentItem(text: "你知道嗎"),
        CardContentItem(text: "我們畢業了欸"),
        CardContentItem(text: "ㄏ"),
        CardContentItem(text: "解脫土撥鼠的掌控了"),
        CardContentItem(text: ":D"),
        CardContentItem(text: ""),
        CardContentItem(text: "上次更新這個app，是在會考前一個月"),
        CardContentItem(text: "因為你的一句話"),
        CardContentItem(text: "「欸你去更新一下那個app啦，"),
        CardContentItem(text: "在我們不講話之前都更新一下嘛」"),
        CardContentItem(text: "我就開始埋頭苦幹"),
        CardContentItem(text: "寫長文"),
        CardContentItem(text: "想新玩法"),
        CardContentItem(text: "做新玩法"),
        CardContentItem(text: "結果你在會考當天才更新 ：）"),
        CardContentItem(text: "會考倒數、會考前的彩蛋、會考當天會發送的訊息"),
        CardContentItem(text: "這些東西都錯過了"),
        CardContentItem(text: "也是 挺猛"),
        CardContentItem(text: "說實話我覺得蠻不被尊重的"),
        CardContentItem(text: ":D"),
        CardContentItem(text: ""),
        CardContentItem(text: "ㄜˊ"),
        CardContentItem(text: "怎麼寫那種很有意境的長文啊"),
        CardContentItem(text: "做不到"),
        CardContentItem(text: ":D"),
        CardContentItem(text: ""),
        CardContentItem(text: "好"),
        CardContentItem(text: "就把我們在這段時間內的經歷都講講好了"),
        CardContentItem(text: ""),
        CardContentItem(text: "從我們認識的時候說起"),
        CardContentItem(text: "回到那個"),
        CardContentItem(text: "兩兩認識，但又對各自留有厚厚面紗的時候"),
        CardContentItem(text: "那天是考中檢的日子"),
        CardContentItem(text: "那時我坐在你前面"),
        CardContentItem(text: "你後面是辛宥樂"),
        CardContentItem(text: "好像是數學課的樣子（不然好像也沒機會可以一直講話）"),
        CardContentItem(text: "那時候你突然說"),
        CardContentItem(text: "「啊！我沒帶證件」"),
        CardContentItem(text: "「完蛋了啦等一下要考中檢」"),
        CardContentItem(text: "「怎麼辦我媽也沒辦法送我的證件過來」"),
        CardContentItem(text: "然後我就一直轉頭過去跟你講話"),
        CardContentItem(text: "這時候我們都還沒有很熟"),
        CardContentItem(text: "甚至整個國一都過去了還講不到10句話"),
        CardContentItem(text: "但也因為這件事"),
        CardContentItem(text: "開啟了後面一年半的事情"),
        CardContentItem(text: "（拜託 國一那個尷尬的黑歷史我不想回憶）"),
        CardContentItem(text: ""),
        CardContentItem(text: "那時候我們還不熟"),
        CardContentItem(text: "校車上也是比較多在講話的時候"),
        CardContentItem(text: "你跟我們坐到前面"),
        CardContentItem(text: "開始講班上的大小事"),
        CardContentItem(text: "最多聽到的就是18又怎樣又怎樣了"),
        CardContentItem(text: "也是從那時候開始"),
        CardContentItem(text: "我們也變得比較常講話"),
        CardContentItem(text: ""),
        CardContentItem(text: "時間來到了2023/3/2晚上9."),
        CardContentItem(text: "那天你突然發了三句"),
        CardContentItem(text: "「香菇、香菇、香菇」"),
        CardContentItem(text: "「這人怪怪的」"),
        CardContentItem(text: "然後附上兩張照片"),
        CardContentItem(text: "分別是自信🈹說："),
        CardContentItem(text: "「你emo喔」"),
        CardContentItem(text: "「我來安慰你」"),
        CardContentItem(text: "我不知道為什麼你會跟我講"),
        CardContentItem(text: "但從那時候開始"),
        CardContentItem(text: "我們才比較常在訊息聊天了"),
        CardContentItem(text: ""),
        CardContentItem(text: "後來"),
        CardContentItem(text: "你的考試考差了"),
        CardContentItem(text: "家裡給的巨大壓力"),
        CardContentItem(text: "對自己學習的成果不如預想"),
        CardContentItem(text: "感覺家人的付出和自己的成果不成正比"),
        CardContentItem(text: "對於理化、數學的無力感"),
        CardContentItem(text: "讓你一次次的崩潰"),
        CardContentItem(text: "也跑來找我訴苦"),
        CardContentItem(text: "半夜1、2.的emo"),
        CardContentItem(text: "也變成那時候的日常"),
        CardContentItem(text: ""),
        CardContentItem(text: "也是在一個稀鬆平常的夜晚"),
        CardContentItem(text: "你突然傳訊息"),
        CardContentItem(text: "「香菇"),
        CardContentItem(text: "這題怎麼寫"),
        CardContentItem(text: "問5個人了他們都不會」"),
        CardContentItem(text: "從這個奇怪的問題開始"),
        CardContentItem(text: "你就開始問我一堆理化問題"),
        CardContentItem(text: "我還幫你整理筆記ㄟ"),
        CardContentItem(text: "雖然你好像沒在看"),
        CardContentItem(text: ""),
        CardContentItem(text: "接下來，童軍露營近在眼前"),
        CardContentItem(text: "為了練舞和班導起爭執"),
        CardContentItem(text: "為了出演努力準備"),
        CardContentItem(text: "然後前一天還跟我討我跟10的聊天記錄"),
        CardContentItem(text: "💩❓"),
        CardContentItem(text: "到了童軍露營當天"),
        CardContentItem(text: "每個人都滿心期待"),
        CardContentItem(text: "我也不例外"),
        CardContentItem(text: "期待的是童軍「露營」"),
        CardContentItem(text: "但一下車 教官就讓我們知道是童「軍」露營"),
        CardContentItem(text: "「拔掉你的口罩」"),
        CardContentItem(text: "「綁好你的水壺」"),
        CardContentItem(text: "「等一下就給我大聲喊，"),
        CardContentItem(text: "喊到你們燒聲為止」"),
        CardContentItem(text: "結果我都動嘴巴而已:D"),
        CardContentItem(text: "接下來"),
        CardContentItem(text: "到了晚上"),
        CardContentItem(text: "每個班開始唱歌"),
        CardContentItem(text: "這時候才意識到"),
        CardContentItem(text: "原來這隻蛇人也沒有很差"),
        CardContentItem(text: "該玩的也會讓我們玩"),
        CardContentItem(text: "到了我們上台的時候"),
        CardContentItem(text: "我跟你還在打賭"),
        CardContentItem(text: "「猜拳輸的下去拉教官上來唱歌」"),
        CardContentItem(text: "結果老師說了不能這樣"),
        CardContentItem(text: "：（"),
        CardContentItem(text: "但上台後大家還是玩得很開心"),
        CardContentItem(text: "該唱歌的唱歌"),
        CardContentItem(text: "跳舞的跳舞"),
        CardContentItem(text: "連舞台都被跳到在震動"),
        CardContentItem(text: "雖然沒得名，但玩得真的很開心 :D"),
        CardContentItem(text: "後來洗澡的時候"),
        CardContentItem(text: "小公主的水管爆了"),
        CardContentItem(text: "還影響到你"),
        CardContentItem(text: "有夠雖：）"),
        CardContentItem(text: "而且我還跟你借乾洗髮"),
        CardContentItem(text: "第二天你拿到的時候"),
        CardContentItem(text: "你："),
        CardContentItem(text: "・ࡇ・"),
        CardContentItem(text: "「怎麼少那麼多」"),
        CardContentItem(text: "相當抱歉...😦"),
        CardContentItem(text: "然後到了第二天"),
        CardContentItem(text: "那隻蛇突然對我們超好"),
        CardContentItem(text: "路隊有排就行"),
        CardContentItem(text: "課有上就好"),
        CardContentItem(text: "我還懷疑他是不是吃錯藥:D"),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "重點還是在晚上"),
        CardContentItem(text: "營火晚會"),
        CardContentItem(text: "你上去跳舞"),
        CardContentItem(text: "本來還要戴那個像素眼鏡"),
        CardContentItem(text: "可惜的是後來沒有"),
        CardContentItem(text: "反正下台之後也是玩很瘋"),
        CardContentItem(text: "", image: Image("Camping1")),
        CardContentItem(text: "", image: Image("Camping2")),
        CardContentItem(text: "然後接下來就是"),
        CardContentItem(text: "蠟燭"),
        CardContentItem(text: "許願"),
        CardContentItem(text: "我那時候許什麼"),
        CardContentItem(text: "我好像也忘ㄌ"),
        CardContentItem(text: "", image: Image("Camping3")),
        CardContentItem(text: ""),
        CardContentItem(text: "最後一天"),
        CardContentItem(text: "烤肉的時候"),
        CardContentItem(text: "我們組的火一直升不起來"),
        CardContentItem(text: "我還跑去你們那邊拿你們吃剩的"),
        CardContentItem(text: ":D"),
        CardContentItem(text: "反正是挺可憐的就是"),
        CardContentItem(text: ""),
        CardContentItem(text: "接下來"),
        CardContentItem(text: "到了4月"),
        CardContentItem(text: "你還是覺得自信🈹很煩"),
        CardContentItem(text: "我也不知道那時候哪來的勇氣"),
        CardContentItem(text: "就創了一個帳號去搞他"),
        CardContentItem(text: ":D"),
        CardContentItem(text: "也就是人見人愛的婷涵"),
        CardContentItem(text: "一開始我去玩牠"),
        CardContentItem(text: "我以為要很久，搞不好還不會成功"),
        CardContentItem(text: "結果他23小時就上鉤了"),
        CardContentItem(text: "😦"),
        CardContentItem(text: "你還寫小說ㄟ"),
        CardContentItem(text: "然後創完帳號"),
        CardContentItem(text: "我跟你一直在那邊玩顏文字"),
        CardContentItem(text: "還變成我用一堆表符改不回來"),
        CardContentItem(text: "還有一個"),
        CardContentItem(text: "4/16"),
        CardContentItem(text: "我在墾丁"),
        CardContentItem(text: "他在那裡發情"),
        CardContentItem(text: "晚上你在教歷史"),
        CardContentItem(text: "我人不在家"),
        CardContentItem(text: "甚至沒辦法找到課本"),
        CardContentItem(text: "虧我那時候還有帶回家欸：（"),
        CardContentItem(text: "但我有做筆記👌🏻", image: Image("HistoryNote")),
        CardContentItem(text: "看我多認真啊"),
        CardContentItem(text: "而且那時候你說要電話的時候我有嚇到"),
        CardContentItem(text: "我那還是第一次跟女生講電話💩"),
        CardContentItem(text: "在這件事之後我跟你就都用婷涵的帳號聊天了"),
        CardContentItem(text: "欸而且"),
        CardContentItem(text: "後來不是我自己會怕"),
        CardContentItem(text: "然後就跟他分了嗎"),
        CardContentItem(text: "超好笑俗辣一個✅"),
        CardContentItem(text: ""),
        CardContentItem(text: "好吧"),
        CardContentItem(text: "5月我也想不起來有什麼比較大的事"),
        CardContentItem(text: "大概就考試ㄅ"),
        CardContentItem(text: "直接跳到六月唄"),
        CardContentItem(text: "那時候剛放暑假"),
        CardContentItem(text: "耳環事件💩💩💩"),
        CardContentItem(text: "整個暑假都沒講幾句話"),
        CardContentItem(text: "然後倒暑輔的時候"),
        CardContentItem(text: "我真的很EY你會跟我講話😦"),
        CardContentItem(text: "好反正"),
        CardContentItem(text: "之後應該是有和好很多了"),
        CardContentItem(text: "吧"),
        CardContentItem(text: ":D"),
        CardContentItem(text: ""),
        CardContentItem(text: "10月底時學校舉辦校慶運動會"),
        CardContentItem(text: "你幫辛綁頭髮"),
        CardContentItem(text: "我還幫你拍一張眼睛ㄆㄧㄚˊ掉的照片"),
        CardContentItem(text: ":D", image: Image("SchoolFail")),
        CardContentItem(text: "然後"),
        CardContentItem(text: "那時候好像沒有什麼交集"),
        CardContentItem(text: "我跟你拍的照片也沒給我"),
        CardContentItem(text: ""),
        CardContentItem(text: "然後接下來是"),
        CardContentItem(text: "11月的畢旅"),
        CardContentItem(text: "我那時候還說要女裝"),
        CardContentItem(text: "你跟蔡聿庭還有陳家霈都超積極要給我穿"),
        CardContentItem(text: "連真理褲"),
        CardContentItem(text: "百褶裙都出來了"),
        CardContentItem(text: "但後面我還是沒穿:D"),
        CardContentItem(text: "好然後"),
        CardContentItem(text: "大家都滿懷期待的出遊"),
        CardContentItem(text: "我那天還睡不著"),
        CardContentItem(text: "早上一點多才睡著"),
        CardContentItem(text: "然後ㄤ"),
        CardContentItem(text: "第一天去六福村"),
        CardContentItem(text: "吳季詡跟辛宥樂還在那邊一直滑滑步"),
        CardContentItem(text: "而且你的項鍊還被王芊庭弄到我手上"),
        CardContentItem(text: "我超ㄘㄨㄚˋ"),
        CardContentItem(text: "超怕弄不見"),
        CardContentItem(text: "還好後面有找到你 ：）"),
        CardContentItem(text: "晚上的時候去夜市"),
        CardContentItem(text: "你穿楊永仲外套我確實是有嚇到:D"),
        CardContentItem(text: "然後集合的時候我還拿一支超大的煙"),
        CardContentItem(text: "跟教官拍照"),
        CardContentItem(text: "萬一峰在超奇怪的地方躲著"),
        CardContentItem(text: "", image: Image("BigSmoke")),
        CardContentItem(text: "然後晚上的時候"),
        CardContentItem(text: "3班還有人打電話跟你晚安"),
        CardContentItem(text: "接下來就變我打給你"),
        CardContentItem(text: "然後在那裡用google翻譯讓他講話"),
        CardContentItem(text: "好玩"),
        CardContentItem(text: "隔天的行程"),
        CardContentItem(text: "好像也沒什麼交集"),
        CardContentItem(text: "但晚上的時候大家都唱歌唱得很開心"),
        CardContentItem(text: "還有辛宥樂"),
        CardContentItem(text: "擦玻璃🈹 :D"),
        CardContentItem(text: "", videoName: "DancingHsin"),
        CardContentItem(text: "下車之後"),
        CardContentItem(text: "在路上跳舞跳了一個小時"),
        CardContentItem(text: "辛、吳在滑步"),
        CardContentItem(text: "後來去旁邊的寶雅之類的東西"),
        CardContentItem(text: "咱們寬哥還來找你ㄟ"),
        CardContentItem(text: "真是深情"),
        CardContentItem(text: "然後當天晚上玩了真心話大冒險線上版"),
        CardContentItem(text: "我沒被放進轉盤超久"),
        CardContentItem(text: "到要結束了你們才發現"),
        CardContentItem(text: ":D"),
        CardContentItem(text: "第三天的景點"),
        CardContentItem(text: "先去不知道叫什麼的地方"),
        CardContentItem(text: "然後拍了那個轉圈圈"),
        CardContentItem(text: "", videoName: "PeopleTurning"),
        CardContentItem(text: "還有這個"),
        CardContentItem(text: "", image: Image("PeopleCircle")),
        CardContentItem(text: "接下來到鹿港老街"),
        CardContentItem(text: "在那個巷子裡"),
        CardContentItem(text: "玩了超久"),
        CardContentItem(text: "欸那三天"),
        CardContentItem(text: "真的超好玩"),
        CardContentItem(text: ""),
        CardContentItem(text: "一樣是11月"),
        CardContentItem(text: "那時候音樂課要表演"),
        CardContentItem(text: "我帶一堆螢光棒"),
        CardContentItem(text: "結果校車上被拆來玩"),
        CardContentItem(text: "你綁兩邊", image: Image("PlayingGlowSticks")),
        CardContentItem(text: "洪秉謙綁頭上一支", image: Image("PlayingGlowSticks2")),
        CardContentItem(text: "玩得超瘋"),
        CardContentItem(text: "還有張庭勛在上香", videoName: "IncenseStick"),
        CardContentItem(text: "這更好笑", image: Image("PlayingGlowSticks")),
        CardContentItem(text: "還有演唱會"),
        CardContentItem(text: "", videoName: "Concert"),
        CardContentItem(text: "❓", image: Image("PlayingGlowSticks3")),
        CardContentItem(text: "那天應該是三年來校車上玩最瘋的一天"),
        CardContentItem(text: ""),
        CardContentItem(text: "到12月"),
        CardContentItem(text: "我生日前一天"),
        CardContentItem(text: "你在手上用簽字筆寫生辰快樂"),
        CardContentItem(text: "超好笑"),
        CardContentItem(text: "張庭勛的腿還遭殃"),
        CardContentItem(text: "接下來是我的生日"),
        CardContentItem(text: "相當的重要"),
        CardContentItem(text: "那個手機殼"),
        CardContentItem(text: "沒講完的生日賀卡"),
        CardContentItem(text: "一疊香菇便利貼"),
        CardContentItem(text: "欸這個我到現在都還沒用💩"),
        CardContentItem(text: "還有幾張手繪"),
        CardContentItem(text: "我超感動"),
        CardContentItem(text: "少數的生日禮物😦"),
        CardContentItem(text: ""),
        CardContentItem(text: "再個天就是睡覺骨牌了"),
        CardContentItem(text: "", videoName: "FourMenSleeping"),
        CardContentItem(text: ""),
        CardContentItem(text: "還記得這個ㄇ"),
        CardContentItem(text: "", image: Image("NailLove")),
        CardContentItem(text: ""),
        CardContentItem(text: "好的"),
        CardContentItem(text: "轉眼間"),
        CardContentItem(text: "時間就來到2024"),
        CardContentItem(text: "會考的壓力也愈來愈大"),
        CardContentItem(text: "你：敷衍 塑膠 不理人"),
        CardContentItem(text: "🙂"),
        CardContentItem(text: "", image: Image("MadeByPlastic")),
        CardContentItem(text: "糟糕至極"),
        CardContentItem(text: "💩💩"),
        CardContentItem(text: ""),
        CardContentItem(text: "欸對你還記得這個嗎"),
        CardContentItem(text: "這筆記超漂亮"),
        CardContentItem(text: "", image: Image("HistoryNote2")),
        CardContentItem(text: "謝謝la～"),
        CardContentItem(text: ""),
        CardContentItem(text: "接下來是2月"),
        CardContentItem(text: "放寒假"),
        CardContentItem(text: "一樣消失"),
        CardContentItem(text: "但不一樣的是你要生日了"),
        CardContentItem(text: "作為這麼好的同學當然是要幫你準備禮物"),
        CardContentItem(text: "絕對是這樣的對吧"),
        CardContentItem(text: "那時候我想超久"),
        CardContentItem(text: "我完全不知道送你什麼"),
        CardContentItem(text: "：雖然說你給我的大概100以內"),
        CardContentItem(text: "：但感覺太敷衍也不好"),
        CardContentItem(text: "：吼到底要送什麼啦"),
        CardContentItem(text: "然後我也忘記為什麼會想到送這個"),
        CardContentItem(text: "反正那時候我想到要做的時候已經剩下20天了"),
        CardContentItem(text: "再加上要寫稿 要做玩法 要藏彩蛋 要學新東西"),
        CardContentItem(text: "我本來還預計要提前5天給你"),
        CardContentItem(text: "所以那時候真的超趕"),
        CardContentItem(text: "ㄞ反正"),
        CardContentItem(text: "之後是做出來的對吧"),
        CardContentItem(text: "但會考前的更新是有點可憐就是了"),
        CardContentItem(text: "💩"),
        CardContentItem(text: "接下來過完寒假"),
        CardContentItem(text: "會考剩最後100天了"),
        CardContentItem(text: "變成快死了的會考牲"),
        CardContentItem(text: "🤡"),
        CardContentItem(text: ""),
        CardContentItem(text: "然後啊"),
        CardContentItem(text: "三月 四月"),
        CardContentItem(text: "好像沒有什麼東西"),
        CardContentItem(text: "喔對"),
        CardContentItem(text: "你有做畢冊欸"),
        CardContentItem(text: "好看"),
        CardContentItem(text: "雖然中間幹事聽說挺多"),
        CardContentItem(text: "但好看 :D"),
        CardContentItem(text: "五月"),
        CardContentItem(text: "我也不知道有什麼"),
        CardContentItem(text: "後來就會考了"),
        CardContentItem(text: "會考那兩天"),
        CardContentItem(text: "應該也是沒發生什麼"),
        CardContentItem(text: "就是中午很難睡而已 :D"),
        CardContentItem(text: "如果有應該是我忘了而已"),
        CardContentItem(text: ""),
        CardContentItem(text: "後來會考完"),
        CardContentItem(text: "大家都在玩手機 看電影 玩桌遊"),
        CardContentItem(text: "說實在挺空虛的💩"),
        CardContentItem(text: "反正我是沒想到會考後會那麼無聊"),
        CardContentItem(text: "然後不知不覺"),
        CardContentItem(text: "就要畢業了"),
        CardContentItem(text: "紅樓夢結束的那一刻"),
        CardContentItem(text: "畢業紀念冊發下的那一刻"),
        CardContentItem(text: "彷彿都在向我們說"),
        CardContentItem(text: "「能和同學相處的時間不多了，"),
        CardContentItem(text: "最後的這一點時光，"),
        CardContentItem(text: "好好珍惜」"),
        CardContentItem(text: ""),
        CardContentItem(text: "雖然說"),
        CardContentItem(text: "跟你認識了那麼久（小一開始？"),
        CardContentItem(text: "真正熟的時間也從國二開始而已"),
        CardContentItem(text: "半夜的一某"),
        CardContentItem(text: "校車上的八卦"),
        CardContentItem(text: "為了一些無謂的事情爭吵到半夜2."),
        CardContentItem(text: "這些點點滴滴"),
        CardContentItem(text: "即使上了高中、大學"),
        CardContentItem(text: "也會永存於我的心中"),
        CardContentItem(text: "現在看回之前的各種回憶"),
        CardContentItem(text: "不管是開心、生氣"),
        CardContentItem(text: "亦或是尷尬、厭惡"),
        CardContentItem(text: "都是這段友誼中不可或缺的元素"),
        CardContentItem(text: "我們之間的感情"),
        CardContentItem(text: "我很喜歡"),
        CardContentItem(text: "一起發瘋、一起打鬧"),
        CardContentItem(text: "一起玩螢光棒、一起面對情緒"),
        CardContentItem(text: "一起學習、一起玩你畫我猜"),
        CardContentItem(text: "一起討論價值觀、一起在學校度過最後的時光"),
        CardContentItem(text: "最後一起畢業"),
        CardContentItem(text: "一切的一切都是那麼寶貴"),
        CardContentItem(text: "卻又走得那麼快"),
        CardContentItem(text: ""),
        CardContentItem(text: "認識你的這兩年"),
        CardContentItem(text: "被大大小小的回憶填滿"),
        CardContentItem(text: "也正因如此"),
        CardContentItem(text: "這段友誼顯得格外珍貴"),
        CardContentItem(text: "奈何"),
        CardContentItem(text: "時間不曾為誰停下腳步"),
        CardContentItem(text: "再要好的朋友、再珍貴的友誼"),
        CardContentItem(text: "在時間的面前不值一提"),
        CardContentItem(text: "但也希望"),
        CardContentItem(text: "能在畢業後繼續一如既往地聯絡"),
        CardContentItem(text: "不被地緣限制"),
        CardContentItem(text: "不被時間支配"),
        CardContentItem(text: "隨心所欲的聊天"),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "畢業快樂"),
        CardContentItem(text: "或許會考成績不盡理想"),
        CardContentItem(text: "但成績並不代表一個人的成敗"),
        CardContentItem(text: "希望你能在這之後"),
        CardContentItem(text: "仍能保持現在這份心情"),
        CardContentItem(text: "積極的面對每個挑戰"),
        CardContentItem(text: "能夠面對自己的情緒"),
        CardContentItem(text: ""),
        CardContentItem(text: "這段友誼"),
        CardContentItem(text: "在我心中永遠保有一席之地"),
        CardContentItem(text: "不論時間過了多久"),
        CardContentItem(text: "這兩年發生的事情"),
        CardContentItem(text: "是最讓我印象深刻"),
        CardContentItem(text: "也讓我想好好保存在心中的"),
        CardContentItem(text: "也希望之後我們都能在各自開闢的道路上"),
        CardContentItem(text: "發光發熱"),
        CardContentItem(text: ""),
        CardContentItem(text: "最後"),
        CardContentItem(text: "期望你能在喜愛的、擅長的事物上"),
        CardContentItem(text: "找到自己的一席之地"),
        CardContentItem(text: ""),
        CardContentItem(text: "學校將我們聚再一起"),
        CardContentItem(text: "又將我們殘酷的打散"),
        CardContentItem(text: "但或許幾年後的某天"),
        CardContentItem(text: "你會偶然間想起我們在這段時間所經歷的"),
        CardContentItem(text: "會再次點開這個程式"),
        CardContentItem(text: "看看那時候的我們"),
        CardContentItem(text: "到了那時候的我"),
        CardContentItem(text: "是什麼樣的人呢"),
        CardContentItem(text: "到了那時候的你"),
        CardContentItem(text: "又會是什麼樣的人呢"),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "那就"),
        CardContentItem(text: "先醬子唄"),
        CardContentItem(text: "畢業快樂"),
        CardContentItem(text: "🎓"),
        CardContentItem(text: ""),
        CardContentItem(text: "", videoName: "LastVideo"),
        CardContentItem(text: ""),
        CardContentItem(text: "24.6.16  香菇"),
        CardContentItem(text: "")
    ]
    
    let watchMainFirst: [CardContentItem] = [
        CardContentItem(text: "好笑嗎"),
        CardContentItem(text: "鎖都放那裡了"),
        CardContentItem(text: "要就付費解鎖✅")
    ]
}
